### PR TITLE
fix t1 undefined error

### PR DESCRIPTION
**Pull request by dringeis**
I had an error with undefined `t1` so I moved the code up so the `t?` would defined before they are checked.
I also had to give `t1` and `t2` a default value before they are checked in the cases of cold restart or not.

### CODE REVIEW

**Comment by mankoff** [comment]
Can you share what command or commands caused the crash and where the crash occurred?

**Comment by mankoff** [comment]
Push additional changes. Please test this version.

**Review by mankoff — APPROVED** [review]
Seems to work for me now w/o entering any dates. Defaults work.

**Comment by dringeis** [comment]
I was testing it right now and It does not work for me

**Comment by dringeis** [comment]
```bash
dringeis@discover12:~/code/modelE/decks> ../exec/econ -r r09 --template /discover/nobackup/kmankoff/data/landice/E6F40pism -t0 1000-01-01 -t2 1000-03-01 --cold-restart -v -o -np 88
[2023-07-21T17:08:52-04:00] [WARN] [econ] Call: /gpfsm/dnb33/dringeis/code/econ/econ -r r09 --template /discover/nobackup/kmankoff/data/landice/E6F40pism -t0 1000-01-01 -t2 1000-03-01 --cold-restart -v -o -np 88
[2023-07-21T17:08:53-04:00] [INFO] [econ] Checking env...
[2023-07-21T17:08:53-04:00] [INFO] [econ] START set_default
[2023-07-21T17:08:53-04:00] [INFO] [econ] E_ROOT: /discover/nobackup/dringeis
[2023-07-21T17:08:53-04:00] [INFO] [econ] Git commit: unstaged
[2023-07-21T17:08:53-04:00] [INFO] [econ] RC file: /gpfsm/dhome/dringeis/modelErc.default
[2023-07-21T17:08:53-04:00] [INFO] [econ] Num processors: 88
 [2023-07-21T17:08:53-04:00] [ERR] [econ] at: main(), /gpfsm/dnb33/dringeis/code/modelE/exec/econ_includes.sh, line 120
```

**Comment by mankoff** [comment]
Ack. Yes, I caught that error on my computer, but merged before I pushed the fix. Sorry. Please try updating and running again.

**Comment by dringeis** [comment]
It works, thanks!

(your forgot to remove some git `<<<<`, I do it in a minor update)

**Pull request merged**
